name: Android

on:
  workflow_dispatch:

env:
  CMAKE_VERSION: 4.0.2
  BUILD_TYPE: debug

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: cmake;${{env.CMAKE_VERSION}}

      - name: Use SDKs cmake version
        run: |
          echo "${ANDROID_HOME}/cmake/${{env.CMAKE_VERSION}}/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: CMake Configuration
        run: cmake --preset=${{env.BUILD_TYPE}}::android

      - name: CMake Build
        run: cmake --build --preset=${{env.BUILD_TYPE}}::android
