name: Linux GCC

on:
  workflow_dispatch:

env:
  CMAKE_VERSION: 4.0.2
  NINJA_VERSION: 1.12.1
  BUILD_TYPE: debug

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: fedora:42

    steps:
      - name: Update and install dependencies
        run: |
          sudo dnf update -y
          packages=(
              git                  
              unzip                
              gcc gcc-c++        
              SDL3-devel
          )
          sudo dnf install -y ${packages[@]}

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{env.CMAKE_VERSION}}
          ninjaVersion: ${{env.NINJA_VERSION}}

      - name: CMake Configuration
        run: cmake --preset=${{env.BUILD_TYPE}}

      - name: CMake Build
        run: cmake --build --preset=${{env.BUILD_TYPE}}
