name: macOS clang

on:
  workflow_dispatch:

env:
  LLVM_VERSION: 20
  SDL_VERSION: 3.2.14
  BUILD_TYPE: debug

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Install LLVM
        run: |
          brew update
          brew install cmake llvm@${{env.LLVM_VERSION}}
          echo "$(brew --prefix llvm@${{env.LLVM_VERSION}})/bin" >> $GITHUB_PATH
          LLVM_PREFIX=$(brew --prefix llvm@${{env.LLVM_VERSION}})
          echo "Homebrew LLVM prefix: $LLVM_PREFIX"
          echo "LLVM_BIN_PATH=$LLVM_PREFIX/bin" >> $GITHUB_ENV

      - name: Verify Clang Version
        run: |
          echo "Checking Clang version using direct path from Homebrew..."
          "$LLVM_BIN_PATH/clang" --version
          echo "Checking PATH's Clang version (for comparison, might still be AppleClang initially)"
          clang --version

      - name: Setup SDL sdk
        uses: libsdl-org/setup-sdl@main
        with:
          version: ${{env.SDL_VERSION}}

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: CMake Configuration
        env:
          CC: '${{github.env.LLVM_BIN_PATH}}/clang'
          CXX: '${{github.env.LLVM_BIN_PATH}}/clang++'
        run: cmake --preset=${{env.BUILD_TYPE}}

      - name: CMake Build
        run: cmake --build --preset=${{env.BUILD_TYPE}}
