name: macOS clang

on:
  workflow_dispatch:

env:
  LLVM_VERSION: 20
  SDL_VERSION: 3.2.14
  CMAKE_VERSION: 4.0.2
  NINJA_VERSION: 1.12.1
  BUILD_TYPE: debug

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Install LLVM
        run: |
          brew update
          brew install cmake ninja llvm@${{env.LLVM_VERSION}}
          echo "/usr/local/opt/llvm@${{env.LLVM_VERSION}}/bin" >> $GITHUB_PATH
          echo "LDFLAGS=-L/usr/local/opt/llvm@${{env.LLVM_VERSION}}/lib -Wl,-rpath,/usr/local/opt/llvm@${{env.LLVM_VERSION}}/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/usr/local/opt/llvm@${{env.LLVM_VERSION}}/include" >> $GITHUB_ENV

      - name: Setup SDL sdk
        uses: libsdl-org/setup-sdl@main
        with:
          version: ${{env.SDL_VERSION}}

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: CMake Configuration
        run: cmake --preset=${{env.BUILD_TYPE}}

      - name: CMake Build
        run: cmake --build --preset=${{env.BUILD_TYPE}}
