name: macOS clang

on:
  workflow_dispatch:

env:
  XCODE: 16.4
  SDL_VERSION: 3.2.14
  BUILD_TYPE: debug

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Switch Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{env.XCODE}}.app

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup SDL sdk
        uses: libsdl-org/setup-sdl@main
        with:
          version: ${{env.SDL_VERSION}}
          build-type: Release
          pre-release: false

      - name: CMake Configuration
        run: cmake --preset=${{env.BUILD_TYPE}}

      - name: CMake Build
        run: cmake --build --preset=${{env.BUILD_TYPE}}
