name: macOS clang

on:
  workflow_dispatch:

env:
  LLVM_VERSION: 20.1.3
  SDL_VERSION: 3.2.14
  BUILD_TYPE: debug

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: ${{env.LLVM_VERSION}}
          arch: arm64
          directory: ${{github.workspace}}/.llvm
          env: true

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup SDL sdk
        uses: libsdl-org/setup-sdl@main
        with:
          version: ${{env.SDL_VERSION}}
          build-type: Release
          pre-release: false

      - name: CMake Configuration
        run: cmake --preset=${{env.BUILD_TYPE}}

      - name: CMake Build
        run: cmake --build --preset=${{env.BUILD_TYPE}}
