name: macOS clang

on:
  workflow_dispatch:

env:
  LLVM_VERSION: 20
  SDL_VERSION: 3.2.14
  BUILD_TYPE: debug

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Install LLVM via Homebrew
        run: |
          brew upgrade
          brew install llvm@${{env.LLVM_VERSION}}
          echo "PATH=$(brew --prefix llvm@${{env.LLVM_VERSION}})/bin:$PATH" >> $GITHUB_ENV
          echo "LLVM_DIR=$(brew --prefix llvm@${{env.LLVM_VERSION}})/lib/cmake/llvm" >> $GITHUB_ENV
      - name: Verify LLVM version
        run: |
          clang --version
          llvm-config --version

      - name: Setup SDL sdk
        uses: libsdl-org/setup-sdl@main
        with:
          version: ${{env.SDL_VERSION}}

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: CMake Configuration
        run: cmake --preset=${{env.BUILD_TYPE}}

      - name: CMake Build
        run: cmake --build --preset=${{env.BUILD_TYPE}}
