name: Windows MSVC

on:
  workflow_dispatch:

env:
  SDL_VERSION: 3.2.14
  BUILD_TYPE: debug

jobs:
  build:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup VS Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022

      - name: Setup SDL sdk
        uses: libsdl-org/setup-sdl@main
        with:
          version: ${{env.SDL_VERSION}}
          build-type: Release
          pre-release: false

      - name: CMake Configuration
        run: cmake --preset=${{env.BUILD_TYPE}}

      - name: CMake Build
        run: cmake --build --preset=${{env.BUILD_TYPE}}
